In [1]:
from mtcnn.mtcnn import MTCNN

Using TensorFlow backend.


In [2]:
import numpy as np
import cv2
import os
from datetime import datetime

In [3]:
faces = 0
frames = 0

In [4]:
max_faces = 5
max_bbox = np.zeros(4)


In [5]:
max_bbox

array([0., 0., 0., 0.])

In [6]:
detector = MTCNN()

In [174]:
img = cv2.cvtColor(cv2.imread("virat-kohli.png"), cv2.COLOR_BGR2RGB)

In [13]:
bboxes = detector.detect_faces(img)

In [14]:
bboxes

[{'box': [123, 36, 55, 74],
  'confidence': 0.9985446929931641,
  'keypoints': {'left_eye': (138, 66),
   'right_eye': (164, 67),
   'nose': (151, 79),
   'mouth_left': (138, 92),
   'mouth_right': (163, 92)}}]

In [15]:
len(bboxes)

1

In [ ]:
[123, 36, 55, 74]

In [21]:
for bboxe in bboxes:
                    
                
                    bbox = bboxe["box"]
                    print(bbox)
                    bbox = np.array([bbox[0], bbox[1], bbox[0] + bbox[2], bbox[1] + bbox[3]])
                    keypoints = bboxe["keypoints"]
                    #area = (bbox[2] - bbox[0]) * (bbox[3] - bbox[1])
                    print(bbox)
                    print(keypoints)
                    landmarks = keypoints

[123, 36, 55, 74]
[123  36 178 110]
{'left_eye': (138, 66), 'right_eye': (164, 67), 'nose': (151, 79), 'mouth_left': (138, 92), 'mouth_right': (163, 92)}


In [22]:
landmarks

{'left_eye': (138, 66),
 'right_eye': (164, 67),
 'nose': (151, 79),
 'mouth_left': (138, 92),
 'mouth_right': (163, 92)}

In [25]:
landmarks.shape

(10,)

In [23]:
landmarks = np.array([landmarks["left_eye"][0], landmarks["right_eye"][0], landmarks["nose"][0],
                                          landmarks["mouth_left"][0], landmarks["mouth_right"][0],
                                          landmarks["left_eye"][1], landmarks["right_eye"][1], landmarks["nose"][1],
                                          landmarks["mouth_left"][1], landmarks["mouth_right"][1]])

In [26]:
landmarks = landmarks.reshape((2, 5)).T

In [27]:
landmarks

array([[138,  66],
       [164,  67],
       [151,  79],
       [138,  92],
       [163,  92]])

In [28]:
from src.insightface.src.common import face_preprocess

In [34]:
img.shape

(300, 300, 3)

In [89]:
nimg = face_preprocess.preprocess(img,max_bbox, landmarks, image_size='112,112')

In [90]:
nimg.shape

(112, 112, 3)

In [91]:
from mtcnn import MTCNN

from src.insightface.deploy import face_model
from src.com_in_ineuron_ai_detectfaces_mtcnn.Configurations import ConfigurationsPOJO
import warnings
import sys
import dlib
# from src.insightface.deploy import face_model

warnings.filterwarnings('ignore')

sys.path.append('../insightface/deploy')
sys.path.append('../insightface/src/common')
from keras.models import load_model
import face_preprocess
import numpy as np
import pickle
import cv2

In [183]:
image_size = '112,112'
model = "E:/face/src/insightface/models/model-y1-test2/model,0"
#E:\face\src\insightface\models\model-y1-test2\model-0000.params
threshold = 1.24
det = 0
model_filename = '../src/com_in_ineuron_ai_sorting/model_data/mars-small128.pb'

            # # Initialize detector
detector = MTCNN()

            # Initialize faces embedding model
embedding_model = face_model.FaceModel(image_size, model, threshold, det)

embeddings = "./faceEmbeddingModels/embeddings.pickle"
le = "./faceEmbeddingModels/le.pickle"

loading E:/face/src/insightface/models/model-y1-test2/model 0


In [95]:
knownEmbeddings = []
knownNames = []

In [103]:
dataset="E:\face\datasets\train"

In [104]:
imagePaths = list(paths.list_images(dataset))

In [105]:
imagePaths

[]

In [106]:
for (i) in enumerate(imagePaths):
    print(i)

In [ ]:
E:\face\datasets\train\rithin\12941.jpg

In [161]:
imagePath="E:\face\r.jpg"

In [167]:
image_path = cv2.imread("E:\face\r.jpg")

In [156]:
ap = argparse.ArgumentParser()

ap.add_argument("--faces", default=50,
                        help="Number of faces that camera will get")
ap.add_argument("--output", default="../datasets/train/" + "rithin",
                        help="Path to faces output")
ap.add_argument("--dataset", default="../datasets/train/rithin",
                        help="Path to training dataset")

args = vars(ap.parse_args())

In [162]:
for (i, imagePath) in enumerate(imagePaths):
            # extract the person name from the image path
            print("[INFO] processing image {}/{}".format(i + 1, len(imagePaths)))
            name = imagePath.split(os.path.sep)[-2]

In [163]:
imagePaths = list(paths.list_images(args.dataset))

AttributeError: 'dict' object has no attribute 'dataset'

In [159]:
imagePaths = list(paths.list_images(args[dataset]))

KeyError: 'E:\x0cace\\datasets\train'

In [164]:
image

In [133]:
name = imagePath.split(os.path.sep)[-2]

In [134]:
name

'E:\x0cace'

In [169]:
import cv2

In [175]:
img = cv2.cvtColor(cv2.imread("virat-kohli.png"), cv2.COLOR_BGR2RGB)

In [179]:
nimg = cv2.cvtColor(cv2.imread("E:/face/r.jpg"), cv2.COLOR_BGR2RGB)

In [180]:
nimg

array([[[ 83,  85,  97],
        [ 83,  85,  97],
        [ 82,  84,  96],
        ...,
        [ 86,  86,  98],
        [ 85,  85,  97],
        [ 83,  83,  95]],

       [[ 84,  86,  98],
        [ 83,  85,  97],
        [ 83,  85,  97],
        ...,
        [ 86,  86,  98],
        [ 85,  85,  97],
        [ 84,  84,  96]],

       [[ 84,  86,  98],
        [ 83,  85,  97],
        [ 83,  85,  97],
        ...,
        [ 86,  86,  98],
        [ 85,  85,  97],
        [ 85,  85,  97]],

       ...,

       [[ 93,  93, 103],
        [ 92,  92, 102],
        [ 90,  92, 104],
        ...,
        [ 94,  92, 106],
        [ 92,  94, 106],
        [ 91,  95, 104]],

       [[ 93,  93, 103],
        [ 92,  92, 102],
        [ 92,  92, 104],
        ...,
        [ 91,  93, 106],
        [ 92,  95, 102],
        [ 92,  96,  99]],

       [[ 93,  93, 103],
        [ 93,  93, 103],
        [ 92,  92, 104],
        ...,
        [ 88,  94, 106],
        [ 92,  95, 100],
        [ 92,  96,  97]]

In [181]:
nimg = np.transpose(nimg, (2, 0, 1))

In [184]:
face_embedding = embedding_model.get_feature(nimg)

AttributeError: module 'sklearn' has no attribute 'preprocessing'

In [170]:
img = cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2RGB)

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [165]:
nimg = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [36]:
cv2.imwrite("r.jpg", nimg)

True

In [83]:
image_size = '112,112'

In [84]:
model = "E:\face\src\insightface\models\model-y1-test2\model-symbol.json"

In [85]:
threshold = 1.24

In [86]:
det = 0

In [88]:
from src.insightface.deploy import face_model
embedding_model = face_model.FaceModel(image_size,model,threshold,det)

AssertionError: 

In [54]:
from src.insightface.deploy import face_model

image_size = (112, 112)  # Example image size
#model = "model-r50,0"  # Example model prefix and epoch
threshold = 1.24  # Example threshold
det = 0  # Example detection model

embedding_model = face_model.FaceModel(image_size, model, threshold, det)


AttributeError: 'tuple' object has no attribute 'split'

In [43]:
embedding_model = face_model.FaceModel(image_size,model,threshold,det)

loading ./insightface/models/model-y1-test2/model 0


MXNetError: Traceback (most recent call last):
  File "C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\local_filesys.cc", line 209
LocalFileSystem: Check failed: allow_null: :Open "./insightface/models/model-y1-test2/model-symbol.json": No such file or directory

In [55]:
import sys

# from insightface.deploy import face_model
# from insightface.deploy import face_model
# from src.insightface.deploy import face_model
from src.insightface.deploy import face_model

sys.path.append('../insightface/deploy')
sys.path.append('../insightface/src/common')

from imutils import paths
import numpy as np
# import face_model
import pickle
import cv2
import os


In [79]:

image_size = "112,112"
#model = "./insightface/models/model-y1-test2/model,0"
threshold = 1.24
det = 0

In [80]:
embedding_model = face_model.FaceModel(image_size,model,threshold,det)

AssertionError: 

In [81]:
def __init__(self, args):
        self.args = args
        self.image_size = '112,112'
        self.model = "./insightface/models/model-y1-test2/model,0"
        self.threshold = 1.24
        self.det = 0

In [65]:
import argparse

In [82]:
ap = argparse.ArgumentParser()

ap.add_argument("--dataset", default="../datasets/train",
                        help="Path to training dataset")
ap.add_argument("--embeddings", default="faceEmbeddingModels/embeddings.pickle")
        # Argument of insightface
ap.add_argument('--image-size', default='112,112', help='')
ap.add_argument('--model', default='../insightface/models/model-y1-test2/model,0', help='path to load model.')
ap.add_argument('--ga-model', default='', help='path to load model.')
ap.add_argument('--gpu', default=0, type=int, help='gpu id')
ap.add_argument('--det', default=0, type=int,
                        help='mtcnn option, 1 means using R+O, 0 means detect from begining')
ap.add_argument('--flip', default=0, type=int, help='whether do lr flip aug')
ap.add_argument('--threshold', default=1.24, type=float, help='ver dist threshold')
args = ap.parse_args()

usage: ipykernel_launcher.py [-h] [--dataset DATASET]
                             [--embeddings EMBEDDINGS]
                             [--image-size IMAGE_SIZE] [--model MODEL]
                             [--ga-model GA_MODEL] [--gpu GPU] [--det DET]
                             [--flip FLIP] [--threshold THRESHOLD]
ipykernel_launcher.py: error: argument --flip: invalid int value: 'c:\\Users\\Admin\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-19304gCjDKk8rxiN2.json'
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "e:\face\venv\lib\argparse.py", line 2409, in _get_value
    result = type_func(arg_string)
ValueError: invalid literal for int() with base 10: 'c:\\Users\\Admin\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-19304gCjDKk8rxiN2.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\face\venv\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "e:\face\venv\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "e:\face\venv\lib\argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "e:\face\venv\lib\argparse.py", line 1845, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "e:\face\venv\lib\argparse.py", line 2376, in _get_values
    value = self._get_value(action, arg_string)
  File "e:\

TypeError: object of type 'NoneType' has no len()

In [66]:
ap = argparse.ArgumentParser()

In [68]:
ap.add_argument("--faces", default=50,
                       help="Number of faces that camera will get")
ap.add_argument("--output", default="../datasets/train/" + "rithin",
                        help="Path to faces output")

args = vars(ap.parse_args())

ArgumentError: argument --output: conflicting option string: --output